<a href="https://colab.research.google.com/github/elka97/GB_PyTorch/blob/main/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import torch

# def print_tens_info(tensor):
#     print("X :\n%s\n" % tensor)
#     print("X количество измерений:\n%s\n" % tensor.dim())
#     print("X размеры : ",  tensor.size())
#     print("X тип : %s\n" % (tensor.type()))    

In [29]:
# 1. Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5).reshape(3, 4, 5).type(torch.float32)
#  or
x = torch.randn(3, 4, 5).type(torch.float32)
#  or
x = torch.randn(3, 4, 5)


In [31]:
# 2. Выведите его форму (shape)

x.shape

torch.Size([3, 4, 5])

In [32]:
# 3. Приведите его к форме 6х10

x_6x10 = x.reshape(6,10)
print(f"x_6x10: {x_6x10.shape}")
# print_tens_info(x_6x10)

x_6x10: torch.Size([6, 10])


In [35]:
# 4. Создайте случайный IntTensor размера 10

x_int_10 = torch.randn(10).type(torch.int)
# print_tens_info(x_int_10)
x_int_10, x_int_10.shape

(tensor([ 0,  1, -1,  0,  0,  1,  0,  0, -1,  0], dtype=torch.int32),
 torch.Size([10]))

In [36]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

x_6x10.mul(x_int_10)

tensor([[ 0.0000,  0.3520, -1.4167,  0.0000, -0.0000,  1.0267,  0.0000,  0.0000,
         -2.0838, -0.0000],
        [-0.0000, -0.8849,  0.1317, -0.0000, -0.0000, -0.9005,  0.0000, -0.0000,
         -0.4349, -0.0000],
        [ 0.0000,  0.1666, -0.7021, -0.0000, -0.0000,  0.7216,  0.0000, -0.0000,
          0.3098,  0.0000],
        [ 0.0000,  1.9006,  0.5862, -0.0000, -0.0000,  0.3770,  0.0000,  0.0000,
         -0.5012, -0.0000],
        [-0.0000, -1.3180, -0.6654,  0.0000,  0.0000, -1.2642,  0.0000,  0.0000,
          1.4649, -0.0000],
        [ 0.0000, -0.2176,  1.2476, -0.0000,  0.0000,  0.4493, -0.0000, -0.0000,
         -0.1853, -0.0000]])

In [37]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

import numpy as np

res = np.dot(x_6x10, x_6x10.T)
res, res.shape

(array([[17.62826   , -7.3993154 ,  0.75626934,  3.624906  , -1.6040322 ,
         -7.5866914 ],
        [-7.3993154 , 10.452519  , -0.35705656, -0.4006783 , -1.6172895 ,
          3.5245898 ],
        [ 0.75626934, -0.35705656,  4.595899  ,  2.3265622 , -4.4807606 ,
         -0.56635267],
        [ 3.624906  , -0.4006783 ,  2.3265622 , 14.435591  , -6.4904838 ,
         -3.8761623 ],
        [-1.6040322 , -1.6172895 , -4.4807606 , -6.4904838 , 19.723328  ,
         -3.1472256 ],
        [-7.5866914 ,  3.5245898 , -0.56635267, -3.8761623 , -3.1472256 ,
         11.124373  ]], dtype=float32), (6, 6))

In [48]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x=torch.tensor(1.0, requires_grad=True)
z=torch.tensor(0.5, requires_grad=True) # constant ? requires_grad
t=torch.tensor(2.0, requires_grad=True)

y=torch.pow(x,3)+z-75*t
print(y)

# # Оценка возможности получения x, y
# print(x.requires_grad)
# print(z.requires_grad)
# print(t.requires_grad)

# Ищу деривацию, реализованную обратной функцией
y.backward()  

# Просмотр производной (градиента) 
print(x.grad, z.grad, t.grad)

tensor(-148.5000, grad_fn=<SubBackward0>)
tensor(3.) tensor(1.) tensor(-75.)


In [39]:
# 8. Создайте единичный тензор размера 5x6
ones_5x6=torch.ones(5, 6)

ones_5x6, ones_5x6.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]), torch.Size([5, 6]))

In [40]:
# 9. Переведите его в формат numpy

np_ones_5x6 = ones_5x6.numpy()

np_ones_5x6, np_ones_5x6.shape

(array([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=float32), (5, 6))