<a href="https://colab.research.google.com/github/elka97/GB_PyTorch/blob/main/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import torch

In [50]:
# 1. Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5).reshape(3, 4, 5).type(torch.float32)
#  or
x = torch.randn(3, 4, 5).type(torch.float32)
#  or
x = torch.randn(3, 4, 5)

x

tensor([[[ 0.9676, -0.3522,  0.2370,  2.2477, -0.4627],
         [ 0.0780, -1.2731, -0.9257, -0.5893,  0.9691],
         [ 0.5518,  0.1204, -1.0953, -1.2021,  1.0678],
         [ 1.5050,  0.7676, -1.9985, -1.9140,  0.5024]],

        [[ 0.1379, -0.2519, -1.2963,  0.8928,  0.7607],
         [ 0.8108, -1.0534,  1.5163, -0.1846,  0.4256],
         [-0.3547, -0.6275, -0.3603, -0.3952, -0.8299],
         [ 0.2939, -1.3375,  0.9876,  0.3350, -0.0662]],

        [[ 0.5962,  1.2552,  0.5386,  0.5119, -0.9258],
         [ 1.3504, -1.7518,  0.4368, -0.3681,  0.1412],
         [-1.1136, -1.7405,  0.2511, -1.0532, -0.9230],
         [ 1.6480,  0.6702,  0.6710,  0.2287,  1.3262]]])

In [51]:
# 2. Выведите его форму (shape)

x.shape

torch.Size([3, 4, 5])

In [53]:
# 3. Приведите его к форме 6х10

x_6x10 = x.reshape(6,10)
x_6x10.shape

torch.Size([6, 10])

In [54]:
# 4. Создайте случайный IntTensor размера 10

x_int_10 = torch.randn(10).type(torch.int)
x_int_10, x_int_10.shape

(tensor([ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0], dtype=torch.int32),
 torch.Size([10]))

In [55]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

x_6x10.mul(x_int_10)

tensor([[ 0.0000, -0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000,  0.9257,
         -0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.0000, -0.0000,  0.0000,  0.0000,  0.0000,  1.9985,
         -0.0000,  0.0000],
        [ 0.0000, -0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.0000, -1.5163,
         -0.0000,  0.0000],
        [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.9876,
          0.0000, -0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000, -0.4368,
         -0.0000,  0.0000],
        [-0.0000, -0.0000,  0.0000, -0.0000, -0.0000,  0.0000,  0.0000, -0.6710,
          0.0000,  0.0000]])

In [56]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

import numpy as np

res = np.dot(x_6x10, x_6x10.T)
res, res.shape

(array([[10.152926  , -0.35936558,  2.0918453 , -0.16200888,  4.1264677 ,
         -2.5407004 ],
        [-0.35936558, 14.868587  , -0.8470048 , -3.520337  , -1.1234626 ,
          1.0637354 ],
        [ 2.0918453 , -0.8470048 ,  7.420483  ,  2.6469147 ,  2.551424  ,
          0.48703986],
        [-0.16200888, -3.520337  ,  2.6469147 ,  4.4617434 ,  2.4116158 ,
          2.818503  ],
        [ 4.1264677 , -1.1234626 ,  2.551424  ,  2.4116158 ,  8.578826  ,
         -0.9503063 ],
        [-2.5407004 ,  1.0637354 ,  0.48703986,  2.818503  , -0.9503063 ,
         11.719983  ]], dtype=float32), (6, 6))

In [57]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x=torch.tensor(1.0, requires_grad=True)
z=torch.tensor(0.5, requires_grad=True) # constant ... requires_grad?
t=torch.tensor(2.0, requires_grad=True)

y=torch.pow(x,3)+z-75*t
print(y)

# # Оценка возможности получения x, y
# print(x.requires_grad)
# print(z.requires_grad)
# print(t.requires_grad)

# Ищу деривацию, реализованную обратной функцией
y.backward()  

# Просмотр производной (градиента) 
print(x.grad, z.grad, t.grad)

tensor(-148.5000, grad_fn=<SubBackward0>)
tensor(3.) tensor(1.) tensor(-75.)


In [58]:
# 8. Создайте единичный тензор размера 5x6
ones_5x6=torch.ones(5, 6)

ones_5x6, ones_5x6.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]), torch.Size([5, 6]))

In [59]:
# 9. Переведите его в формат numpy

np_ones_5x6 = ones_5x6.numpy()

np_ones_5x6, np_ones_5x6.shape

(array([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=float32), (5, 6))