<a href="https://colab.research.google.com/github/elka97/GB_PyTorch/blob/main/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))    

In [5]:
# 1. Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5).reshape(3, 4, 5).type(torch.float32)
# print_tens_info(x)
#  or
x = torch.randn(3, 4, 5).type(torch.float32)
# print_tens_info(x)
#  or
x = torch.randn(3, 4, 5)
# print_tens_info(x)

In [6]:
# 2. Выведите его форму (shape)


# print(f"shape: {x.shape}")
x.shape

torch.Size([3, 4, 5])

In [7]:
# 3. Приведите его к форме 6х10

x_6x10 = x.reshape(6,10)
print(f"x_6x10: {x_6x10.shape}")
print_tens_info(x_6x10)

x_6x10: torch.Size([6, 10])
X :
tensor([[-0.8157,  0.0916, -0.3417,  1.4263, -0.6415, -0.2731, -0.2430,  0.1476,
         -0.9480,  0.4363],
        [ 0.5519, -0.7552, -0.7396,  1.7069, -0.2224,  0.5381,  0.7213,  1.8639,
         -0.5514,  1.5519],
        [ 0.2960,  1.0187,  2.1866, -1.4652, -0.9282,  0.9568, -3.2120,  0.2439,
          0.5133, -0.6855],
        [-0.2906,  0.6411, -0.2788,  0.3228, -0.3149, -1.2992,  0.7451, -1.0808,
          1.2963,  1.2163],
        [ 1.0958, -1.0530,  0.1705, -0.7803,  0.1528,  0.6034, -1.2075, -0.5665,
          0.3291,  0.0276],
        [-0.3947, -1.9039, -1.6601, -1.1468,  0.2760,  0.1421,  0.5738,  0.9641,
         -0.5208, -0.8576]])

X количество измерений:
2

X размеры :  torch.Size([6, 10])
X тип : torch.FloatTensor



In [8]:
# 4. Создайте случайный IntTensor размера 10

x_int_10 = torch.randn(10).type(torch.int)
print_tens_info(x_int_10)

X :
tensor([ 0,  0,  0,  0,  0,  2,  0, -2,  0, -1], dtype=torch.int32)

X количество измерений:
1

X размеры :  torch.Size([10])
X тип : torch.IntTensor



In [9]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

x_6x10.mul(x_int_10)

tensor([[-0.0000,  0.0000, -0.0000,  0.0000, -0.0000, -0.5463, -0.0000, -0.2952,
         -0.0000, -0.4363],
        [ 0.0000, -0.0000, -0.0000,  0.0000, -0.0000,  1.0763,  0.0000, -3.7277,
         -0.0000, -1.5519],
        [ 0.0000,  0.0000,  0.0000, -0.0000, -0.0000,  1.9137, -0.0000, -0.4879,
          0.0000,  0.6855],
        [-0.0000,  0.0000, -0.0000,  0.0000, -0.0000, -2.5984,  0.0000,  2.1617,
          0.0000, -1.2163],
        [ 0.0000, -0.0000,  0.0000, -0.0000,  0.0000,  1.2068, -0.0000,  1.1330,
          0.0000, -0.0276],
        [-0.0000, -0.0000, -0.0000, -0.0000,  0.0000,  0.2842,  0.0000, -1.9282,
         -0.0000,  0.8576]])

In [10]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

import numpy as np

res = np.dot(x_6x10, x_6x10.T)
res, res.shape

(array([[ 4.480958  ,  3.4631703 , -2.6203327 ,  0.36956802, -2.5145395 ,
         -1.0142171 ],
        [ 3.4631703 , 11.381336  , -7.212125  , -0.82064044, -1.832708  ,
          1.6724705 ],
        [-2.6203327 , -7.212125  , 20.940805  , -4.291692  ,  5.0937834 ,
         -5.4134336 ],
        [ 0.36956802, -0.82064044, -4.291692  ,  7.347633  , -1.9522371 ,
         -3.6174438 ],
        [-2.5145395 , -1.832708  ,  5.0937834 , -1.9522371 ,  5.223027  ,
          0.8777429 ],
        [-1.0142171 ,  1.6724705 , -5.4134336 , -3.6174438 ,  0.8777429 ,
         10.213447  ]], dtype=float32), (6, 6))

In [25]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x=torch.tensor(1.0, requires_grad=True)
z=torch.tensor(0.5, requires_grad=True)
t=torch.tensor(2.0, requires_grad=True)

y=torch.pow(x,3)+z-75*t
print(y)

# Оценка возможности получения x, y
print(x.requires_grad)
print(z.requires_grad)
print(t.requires_grad)
print(y.requires_grad)

# Ищу деривацию, реализованную обратной функцией
y.backward()  

# Просмотр производной (градиента) 
print(f"x'={x.grad}")
print(z.grad)
print(t.grad)

tensor(-148.5000, grad_fn=<SubBackward0>)
True
True
True
True
x'=3.0
tensor(1.)
tensor(-75.)


True
True
True


tensor(3.)
tensor(1.)
tensor(-75.)


In [13]:
# 8. Создайте единичный тензор размера 5x6
ones_5x6=torch.ones(5, 6)

ones_5x6, ones_5x6.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]), torch.Size([5, 6]))

In [14]:
# 9. Переведите его в формат numpy

np_ones_5x6 = ones_5x6.numpy()

np_ones_5x6, np_ones_5x6.shape

(array([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=float32), (5, 6))